### ISSUE TITLE
Failed to load the copy-as-html package

### ISSUE THREAD

**Issue by d-Pixie** [my-codeworks/copy-with-style#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [copy-as-html](https://github.com/my-codeworks/copy-as-html) package 0.2.0

### Stack Trace

Failed to load the copy-as-html package

```
At Unexpected token export

SyntaxError: Unexpected token export
    at Module._compile (/app.asar/src/native-compile-cache.js:79:40)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/pixie/projects/copy-as-html/lib/rtf_generator.js:3:35)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/pixie/projects/copy-as-html/lib/copy-as-html.js:6:45)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:548:30)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:335:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -6:56.8.0 editor:move-to-first-character-of-line (input.hidden-input)
  2x -6:56.6.0 editor:newline (input.hidden-input)
  2x -6:56.2.0 core:move-up (input.hidden-input)
     -6:54.2.0 editor:newline (input.hidden-input)
     -6:52.1.0 core:backspace (input.hidden-input)
     -6:50.4.0 core:move-up (input.hidden-input)
     -6:50.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -6:49.9.0 editor:newline (input.hidden-input)
     -6:42.8.0 core:paste (input.hidden-input)
     -6:30.4.0 autocomplete-plus:confirm (input.hidden-input)
     -6:29.1.0 editor:newline (input.hidden-input)
     -6:16.1.0 core:save (input.hidden-input)
     -1:21.4.0 command-palette:toggle (input.hidden-input)
     -1:13.5.0 settings-view:view-installed-packages (input.hidden-input)
     -0:54 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:47.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.1 
copy-as-html 0.2.0 
copy-as-rtf 0.9.3 
file-types 0.5.5 
highlight-selected 0.13.1 
intentions 1.1.2 
language-docker 1.1.7 
language-javascript-jsx 0.3.7 
language-slim 0.5.0 
linter 2.1.4 
linter-docker 0.2.0 
linter-jsonlint 1.3.0 
linter-pycodestyle 2.0.2 
linter-rubocop 2.1.1 
linter-ui-default 1.2.3 
railscast-theme 0.3.0 
red-wavy-underline 0.3.3 
Stylus 3.1.0 
```

**Comment by d-Pixie** [comment]
Was caused by a comment at the top of the RTF module that came before the `"use babel";` pragma. Fixed in v0.2.1
