### ISSUE TITLE
Uncaught Error: spawnSync /bin/sh EPIPE

### ISSUE THREAD

**Issue by aikramer2** [my-codeworks/copy-with-style#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [copy-with-style](https://github.com/my-codeworks/copy-with-style) package 1.1.0

### Stack Trace

Uncaught Error: spawnSync /bin/sh EPIPE

```
At child_process.js:538

Error: spawnSync /bin/sh EPIPE
    at exports._errnoException (util.js:1026:11)
    at spawnSync (child_process.js:473:20)
    at execSync (child_process.js:529:13)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:680:22)
    at Object.execute (/packages/copy-with-style/lib/main.js:37:12)
    at Object.copy_done (/packages/copy-with-style/lib/main.js:48:19)
    at HTMLgenerator.finalize (/packages/copy-with-style/lib/html_generator.js:54:10)
    at Editor.finalize (/packages/copy-with-style/lib/atom_editor.js:67:10)
    at Editor.new_scroll_position (/packages/copy-with-style/lib/atom_editor.js:110:44)
    at Function.module.exports.Emitter.simpleDispatch (/Users/aaronkramer1/Downloads/Flight/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Users/aaronkramer1/Downloads/Flight/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditorPresenter.module.exports.TextEditorPresenter.emitDidUpdateState (/Users/aaronkramer1/Downloads/Flight/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:92:35)
    at TextEditorPresenter.module.exports.TextEditorPresenter.toggleCursorBlink (/Users/aaronkramer1/Downloads/Flight/Atom.app/Contents/Resources/app/src/text-editor-presenter.js:1853:25)
```

### Commands

```
     -6:11.5.0 core:copy (input.hidden-input)
     -6:04.7.0 core:select-all (input.hidden-input)
     -6:00.3.0 copy-with-style:checkSelection (input.hidden-input)
     -5:57.2.0 core:copy (input.hidden-input)
     -5:48.6.0 core:select-all (input.hidden-input)
     -5:45.2.0 copy-with-style:copy (input.hidden-input)
     -4:42.6.0 core:confirm (input.hidden-input)
     -3:45.3.0 core:select-all (input.hidden-input)
     -3:43.7.0 core:copy (input.hidden-input)
     -3:05.0 core:select-all (input.hidden-input)
     -1:59.5.0 core:undo (input.hidden-input)
     -1:43.1.0 core:select-all (input.hidden-input)
     -1:39.6.0 copy-with-syntax:copy (input.hidden-input)
     -1:31.8.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:23 core:select-all (input.hidden-input)
     -0:20.7.0 copy-with-style:preset1 (input.hidden-input)
```

### Non-Core Packages

```
copy-with-style 1.1.0 
copy-with-syntax 0.0.3 
```

**Comment by d-Pixie** [comment]
Looks like you are using an external command, what command is it?
